### Necessário para pegar o token

### Post
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{
    "username": "qwe",
    "password": "qwe"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}

### teste de inserção de curso
POST http://localhost:40000/insertCurso HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "cursoid": 0,
    "codigo": "ENC",
    "descricao": "Bacharelado em Engenharia Civil",
    "ativo": true,
    "deleted": false
}

### teste de buscar todos os cursos
GET http://localhost:40000/getAllCursos HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
}

### teste de buscar curso por ID
GET http://localhost:40000/getCursoByID/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

### teste de atualização de curso
PUT http://localhost:40000/updateCurso/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{
    "codigo": "ENM",
    "descricao": "Bacharelado em Engenharia Mecânica",
    "ativo": true,
    "deleted": false
}

### teste de atualização de curso
DELETE http://localhost:40000/deleteCurso/1 HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}